### ISSUE TITLE
Deleting a section causes error

### ISSUE THREAD

**Issue by yitongzhang** [charliecf/web-patterns#32]
<img width="1060" alt="screenshot 2017-07-26 23 16 17" src="https://user-images.githubusercontent.com/5835973/28656742-8543d08a-7258-11e7-82e2-5ec6828ecbe2.png">

**Comment by yitongzhang** [comment]
actually I just deleted this section nvm lol. How do If ind which section it was that I deleted so that I can restore it again?

fwiw, the ID was 323

**Comment by charliecf** [comment]
This issue seems to lie with a few straggling test database rows that were conflicting with the Rails call on a section name or section location that did not exist.

Deleted those respective rows on Sections table : 2, 3, 294. As well as respective sitelink tags.

Performed the following:

`
DELETE from sections
WHERE id=2, 3

UPDATE sections
SET file_location='content/mailchimp.png'
WHERE id=294

DELETE from sitelinks WHERE id=390;
`
